# Generated by Django 5.1.1 on 2024-09-18 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('message', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('image_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice')),
                ('Invoice_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
